'use client'

import { useState, useRef, useEffect } from 'react'
import { IconChevronLeft, IconChevronRight, IconArrowsMaximize, IconFocus2, IconX } from '@tabler/icons-react'
import { useParams } from 'next/navigation'

export function KernelZoomShowcaseUpscale() {
  const params = useParams()
  const locale = params?.locale === 'de' ? 'de' : 'en'

  const translations = {
    en: {
      title: "UPSCALER",
      subtitle: "Original image generated by chatgpt2 • Enhanced upscale by typus.ai",
      zoomText: "HOVER OR TAP & HOLD TO ENHANCE",
      detailsResolved: "DETAILS RESOLVED: 100%",
      tapAndHold: "TAP AND HOLD",
      enhanced: "ENHANCED",
      imageText: "IMAGE",
      interactiveBtn: "🔬 Try Interactive Upscaler",
      backToPresentation: "◀ Back to Auto-Presentation"
    },
    de: {
      title: "UPSCALER",
      subtitle: "Originalbild generiert durch chatgpt2 • Verbessertes Upscaling durch typus.ai",
      zoomText: "HOVER ODER TIPPEN & HALTEN ZUM VERBESSERN",
      detailsResolved: "DETAILS AUFGELÖST: 100%",
      tapAndHold: "DRÜCKEN & HALTEN",
      enhanced: "VERBESSERT",
      imageText: "BILD",
      interactiveBtn: "🔬 Interaktiven Upscaler testen",
      backToPresentation: "◀ Zurück zur Präsentation"
    }
  }

  const t = translations[locale]

  // Image array mapping 2K input images to 8K high-res outputs
  const images = [
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 10_07_17.png',
      output: '/upscale-images/ouput/replicate-prediction-e76q9cvbynrmr0cygy4afb13fr.png',
      aspectRatio: 5936 / 4240
    },
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 10_19_29.png',
      output: '/upscale-images/ouput/replicate-prediction-h71ac7x22xrmw0cygxqrehwypw.png',
      aspectRatio: 6144 / 4096
    },
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 10_31_22.png',
      output: '/upscale-images/ouput/replicate-prediction-236gt5q085rmw0cygxw8f8qbgw.png',
      aspectRatio: 6144 / 4096
    },
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 10_36_08.png',
      output: '/upscale-images/ouput/replicate-prediction-vrz0y04cfhrmy0cygz080gmwq4.png',
      aspectRatio: 4480 / 5600
    },
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 10_48_13.png',
      output: '/upscale-images/ouput/replicate-prediction-vhfc3w3vjhrmt0cygyw95xmw8m.png',
      aspectRatio: 4480 / 5600
    },
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 11_13_32.png',
      output: '/upscale-images/ouput/replicate-prediction-jqyf483s9drmy0cygz6rt8p08g.png',
      aspectRatio: 5600 / 4480
    },
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 11_31_00.png',
      output: '/upscale-images/ouput/replicate-prediction-cecmtn8qq5rmy0cygyxrndemcg.png',
      aspectRatio: 5600 / 4480
    },
    {
      input: '/upscale-images/input/ChatGPT Image 2. Juni 2026, 11_35_42.png',
      output: '/upscale-images/ouput/replicate-prediction-rr8jrjn4hxrmy0cygys9s3ykfg.png',
      aspectRatio: 4256 / 5904
    },
    {
      input: '/upscale-images/input/ChatGPT Image 29. Mai 2026, 09_51_31.png',
      output: '/upscale-images/ouput/replicate-prediction-hywt9y7ak1rmt0cygy18vd0dq8.png',
      aspectRatio: 5248 / 4800
    },
  ]

  const [activeIndex, setActiveIndex] = useState(0)
  const [mode, setMode] = useState<'presentation' | 'interactive'>('presentation')
  const [isZoomed, setIsZoomed] = useState(false)
  const [boxCoords, setBoxCoords] = useState({ x: 50, y: 50 })
  const [containerRect, setContainerRect] = useState({ width: 960, height: 410 })
  const containerRef = useRef<HTMLDivElement>(null)
  const [isHovered, setIsHovered] = useState(false)

  // Monitor container bounding rect for pixel-perfect image alignment inside Focus Box
  useEffect(() => {
    const updateRect = () => {
      if (containerRef.current) {
        const rect = containerRef.current.getBoundingClientRect()
        setContainerRect({ width: rect.width, height: rect.height })
      }
    }
    updateRect()
    window.addEventListener('resize', updateRect)
    const timer = setTimeout(updateRect, 100)
    return () => {
      window.removeEventListener('resize', updateRect)
      clearTimeout(timer)
    }
  }, [containerRef, mode, activeIndex])

  // Block the floating email buzzer when in interactive mode or hovering the container
  useEffect(() => {
    if (mode === 'interactive' || isHovered) {
      window.dispatchEvent(new CustomEvent('toggle-buzzer-visibility', { detail: { visible: false } }))
      return () => {
        window.dispatchEvent(new CustomEvent('toggle-buzzer-visibility', { detail: { visible: true } }))
      }
    }
  }, [mode, isHovered])

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (isZoomed || mode === 'presentation') return
    const rect = e.currentTarget.getBoundingClientRect()
    const x = ((e.clientX - rect.left) / rect.width) * 100
    const y = ((e.clientY - rect.top) / rect.height) * 100
    
    const clampedX = Math.max(15, Math.min(85, x))
    const clampedY = Math.max(25, Math.min(75, y))
    
    setBoxCoords({ x: clampedX, y: clampedY })
  }

  const handlePrev = (e: React.MouseEvent) => {
    e.stopPropagation()
    setActiveIndex((prev) => (prev - 1 + images.length) % images.length)
  }

  const handleNext = (e: React.MouseEvent) => {
    e.stopPropagation()
    setActiveIndex((prev) => (prev + 1) % images.length)
  }

  const handleContainerClick = () => {
    if (mode === 'presentation') {
      setMode('interactive')
      setIsZoomed(false)
      setBoxCoords({ x: 50, y: 50 })
    }
  }

  const currentAspectRatio = images[activeIndex].aspectRatio
  const boxSize = isZoomed ? 320 : 220
  const boxLeft = isZoomed 
    ? (containerRect.width * 0.5 - 160) 
    : ((boxCoords.x / 100) * containerRect.width - 110)
  const boxTop = isZoomed 
    ? (containerRect.height * 0.5 - 160) 
    : ((boxCoords.y / 100) * containerRect.height - 110)

  // Pure hardware-accelerated CSS style definitions
  // Background shows input image (ChatGPT 2K) unblurred
  const backgroundStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    userSelect: 'none',
    pointerEvents: 'none',
    transformOrigin: 'center',
    transform: mode === 'presentation'
      ? 'scale(1.08) translate3d(0, 0, 0)'
      : isZoomed
      ? `scale(2.2) translate3d(${(50 - boxCoords.x) * 1.2}%, ${(50 - boxCoords.y) * 1.2}%, 0px)`
      : 'scale(1.0) translate3d(0, 0, 0)',
    filter: 'none', // Blur filter completely removed as requested
    transition: mode === 'presentation'
      ? 'transform 3.0s linear'
      : 'transform 0.45s cubic-bezier(0.25, 1, 0.5, 1)',
    animation: 'kernelZoomFadeIn 0.5s ease-in-out forwards',
  }

  const focusBoxStyle: React.CSSProperties = {
    position: 'absolute',
    left: isZoomed ? '50%' : `${boxCoords.x}%`,
    top: isZoomed ? '50%' : `${boxCoords.y}%`,
    transform: 'translate3d(-50%, -50%, 0px)',
    width: `${boxSize}px`,
    height: `${boxSize}px`,
    borderColor: isZoomed ? 'rgba(255, 255, 255, 1.0)' : 'rgba(255, 255, 255, 0.8)',
    transition: isZoomed
      ? 'left 0.45s cubic-bezier(0.25, 1, 0.5, 1), top 0.45s cubic-bezier(0.25, 1, 0.5, 1), width 0.45s cubic-bezier(0.25, 1, 0.5, 1), height 0.45s cubic-bezier(0.25, 1, 0.5, 1), border-color 0.3s ease'
      : 'left 0.15s cubic-bezier(0.25, 1, 0.5, 1), top 0.15s cubic-bezier(0.25, 1, 0.5, 1), width 0.45s cubic-bezier(0.25, 1, 0.5, 1), height 0.45s cubic-bezier(0.25, 1, 0.5, 1), border-color 0.3s ease',
  }

  // Focus Box shows output image (Typus 8K upscaled) razor sharp
  const innerImageStyle: React.CSSProperties = {
    width: containerRect.width,
    height: containerRect.height,
    position: 'absolute',
    maxWidth: 'none',
    left: `${-boxLeft}px`,
    top: `${-boxTop}px`,
    transform: `scale(${isZoomed ? 2.2 : 1.0}) translate3d(${
      isZoomed ? `${(50 - boxCoords.x) * 1.2}%` : '0%'
    }, ${
      isZoomed ? `${(50 - boxCoords.y) * 1.2}%` : '0%'
    }, 0px)`,
    filter: 'blur(0px) contrast(1.04) brightness(1.01)',
    transition: isZoomed
      ? 'left 0.45s cubic-bezier(0.25, 1, 0.5, 1), top 0.45s cubic-bezier(0.25, 1, 0.5, 1), transform 0.45s cubic-bezier(0.25, 1, 0.5, 1)'
      : 'left 0.15s cubic-bezier(0.25, 1, 0.5, 1), top 0.15s cubic-bezier(0.25, 1, 0.5, 1), transform 0.45s cubic-bezier(0.25, 1, 0.5, 1)',
  }

  return (
    <section className="py-10 md:py-16 bg-[#fcfcfd] dark:bg-neutral-950/20 border-y border-neutral-100 dark:border-neutral-900 overflow-hidden relative" id="kernel-zoom-section-upscale">
      <style>{`
        @keyframes kernelZoomFadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }
      `}</style>
      <div className="max-w-[1600px] mx-auto text-center relative z-10 px-4 sm:px-6 lg:px-8">
        
        {/* Try Interactive Button */}
        {mode === 'presentation' && (
          <div className="mb-4 md:mb-6 flex justify-center">
            <button
              onClick={() => {
                setMode('interactive')
                setIsZoomed(false)
                setBoxCoords({ x: 50, y: 50 })
              }}
              className="bg-white dark:bg-neutral-900 hover:bg-neutral-950 hover:text-white dark:hover:bg-white dark:hover:text-black text-neutral-900 dark:text-white border border-neutral-200 dark:border-neutral-800 px-5 py-2.5 rounded-full text-xs font-bold tracking-wider uppercase shadow-md transition-all duration-300 cursor-pointer active:scale-95 flex items-center gap-2"
            >
              <IconFocus2 size={16} className="text-neutral-800 dark:text-neutral-200 animate-pulse" />
              {t.interactiveBtn}
            </button>
          </div>
        )}

        {/* Viewport wrapper */}
        <div className="w-full relative px-2 sm:px-6 flex justify-center items-center min-h-[300px]">
          <div 
            ref={containerRef}
            onClick={handleContainerClick}
            onMouseMove={handleMouseMove}
            onMouseEnter={() => { 
              setIsHovered(true)
              if (mode === 'interactive') setIsZoomed(true) 
            }}
            onMouseLeave={() => { 
              setIsHovered(false)
              if (mode === 'interactive') setIsZoomed(false) 
            }}
            onMouseDown={() => { if (mode === 'interactive') setIsZoomed(true) }}
            onMouseUp={() => { if (mode === 'interactive') setIsZoomed(false) }}
            onTouchStart={() => { 
              setIsHovered(true)
              if (mode === 'interactive') setIsZoomed(true) 
            }}
            onTouchEnd={() => { 
              setIsHovered(false)
              if (mode === 'interactive') setIsZoomed(false) 
            }}
            style={{ 
              aspectRatio: currentAspectRatio,
              width: `min(100%, calc(90vh * ${currentAspectRatio}))`,
              height: `min(90vh, calc(100% / ${currentAspectRatio}))`
            }}
            className={`relative overflow-hidden border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-xl dark:shadow-black/40 select-none transition-all duration-500 max-w-7xl rounded-none border-x-0 w-full h-auto ${
              mode === 'presentation'
                ? 'cursor-pointer group/pres'
                : 'cursor-zoom-in'
            }`}
          >
            {/* Background Image shows low-res input image */}
            <div className="absolute inset-0 w-full h-full overflow-hidden">
              <img
                key={activeIndex}
                src={images[activeIndex].input}
                style={backgroundStyle}
                className="absolute inset-0 w-full h-full object-cover select-none pointer-events-none origin-center"
                alt="Original low-res input render"
              />
            </div>

            <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-black/20 pointer-events-none" />

            {/* Interactive Mode Zoom Box shows high-res upscaled output image */}
            {mode === 'interactive' && (
              <div
                style={focusBoxStyle}
                className="absolute rounded-[24px] sm:rounded-[32px] border-2 pointer-events-none shadow-[0_0_40px_rgba(0,0,0,0.25)] z-20 flex flex-col justify-between p-3.5 overflow-hidden"
              >
                <div className="absolute inset-0 w-full h-full overflow-hidden -z-10 rounded-[22px] sm:rounded-[30px] bg-neutral-900 pointer-events-none">
                  <img
                    src={images[activeIndex].output}
                    style={innerImageStyle}
                    className="object-cover select-none pointer-events-none origin-center"
                    alt="Upscaled razor-sharp detail focus"
                  />
                </div>

                <div className="flex justify-start">
                  <div className="bg-white text-neutral-900 px-3 py-1 rounded-full text-[9px] sm:text-[10px] font-bold tracking-wider uppercase shadow-md border border-neutral-200/50 flex items-center gap-1.5">
                    {isZoomed && <span className="w-1.5 h-1.5 rounded-full bg-neutral-900 dark:bg-black animate-ping" />}
                    {isZoomed ? t.enhanced : t.tapAndHold}
                  </div>
                </div>

                <div className="flex justify-end">
                  <div className="bg-white text-neutral-900 p-1.5 rounded-full shadow-md border border-neutral-200/50">
                    <IconArrowsMaximize size={14} strokeWidth={2.5} />
                  </div>
                </div>
              </div>
            )}

            {mode === 'interactive' && (
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  setMode('presentation')
                }}
                className="absolute top-4 right-4 bg-white/95 text-neutral-950 px-4 py-2 rounded-full text-[10px] sm:text-xs font-bold tracking-wider uppercase shadow-lg border border-neutral-200/80 hover:bg-neutral-950 hover:text-white transition-all duration-300 z-30 cursor-pointer active:scale-95 flex items-center gap-1.5"
              >
                <IconX size={14} strokeWidth={2.5} />
                {t.backToPresentation}
              </button>
            )}

            <button
              onClick={handlePrev}
              className="absolute left-4 top-1/2 -translate-y-1/2 p-2.5 bg-white/80 dark:bg-black/60 hover:bg-black hover:text-white dark:hover:bg-white dark:hover:border-white dark:hover:text-black text-neutral-800 dark:text-white rounded-full border border-neutral-200 dark:border-neutral-800 shadow-md transition-all duration-300 z-30 cursor-pointer active:scale-95 group/btn"
              aria-label="Previous image"
            >
              <IconChevronLeft size={20} className="group-hover/btn:-translate-x-0.5 transition-transform animate-none" />
            </button>

            <button
              onClick={handleNext}
              className="absolute right-4 top-1/2 -translate-y-1/2 p-2.5 bg-white/80 dark:bg-black/60 hover:bg-black hover:text-white dark:hover:bg-white dark:hover:border-white dark:hover:text-black text-neutral-800 dark:text-white rounded-full border border-neutral-200 dark:border-neutral-800 shadow-md transition-all duration-300 z-30 cursor-pointer active:scale-95 group/btn"
              aria-label="Next image"
            >
              <IconChevronRight size={20} className="group-hover/btn:translate-x-0.5 transition-transform animate-none" />
            </button>
          </div>
        </div>

        {/* Indicators HUD */}
        <div className="flex flex-col sm:flex-row items-center justify-between max-w-7xl mx-auto mt-6 px-4 gap-4 text-neutral-500 dark:text-neutral-400 font-sans text-xs">
          <div className="font-mono text-[11px] uppercase tracking-wider">
            {t.detailsResolved}
          </div>
          
          <div className="flex gap-2.5 items-center">
            {images.map((_, idx) => (
              <button
                key={idx}
                onClick={() => setActiveIndex(idx)}
                className={`h-1.5 rounded-full transition-all duration-500 cursor-pointer ${
                  activeIndex === idx 
                    ? 'bg-neutral-800 dark:bg-white w-6 shadow-sm' 
                    : 'bg-neutral-300 dark:bg-neutral-800 w-1.5 hover:bg-neutral-400'
                }`}
                aria-label={`Go to image ${idx + 1}`}
              />
            ))}
          </div>

          <div className="font-mono text-[11px] uppercase tracking-wider">
            {t.imageText} {activeIndex + 1} / {images.length}
          </div>
        </div>

      </div>
    </section>
  )
}
